#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorks2016")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AdventureWorks2016ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<viewApex> viewApexes
	{
		get
		{
			return this.GetTable<viewApex>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewApex")]
public partial class viewApex
{
	
	private string _Sold_At;
	
	private string _Sold_To;
	
	private string _Account_Number;
	
	private string _Invoice__;
	
	private string _Customer_PO__;
	
	private System.DateTime _Order_Date;
	
	private string _OrderDateText;
	
	private string _DueDateText;
	
	private System.DateTime _Due_Date;
	
	private decimal _Invoice_Total;
	
	public viewApex()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sold At]", Storage="_Sold_At", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Sold_At
	{
		get
		{
			return this._Sold_At;
		}
		set
		{
			if ((this._Sold_At != value))
			{
				this._Sold_At = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sold To]", Storage="_Sold_To", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
	public string Sold_To
	{
		get
		{
			return this._Sold_To;
		}
		set
		{
			if ((this._Sold_To != value))
			{
				this._Sold_To = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Account Number]", Storage="_Account_Number", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Account_Number
	{
		get
		{
			return this._Account_Number;
		}
		set
		{
			if ((this._Account_Number != value))
			{
				this._Account_Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invoice #]", Storage="_Invoice__", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string Invoice__
	{
		get
		{
			return this._Invoice__;
		}
		set
		{
			if ((this._Invoice__ != value))
			{
				this._Invoice__ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer PO #]", Storage="_Customer_PO__", DbType="NVarChar(25)")]
	public string Customer_PO__
	{
		get
		{
			return this._Customer_PO__;
		}
		set
		{
			if ((this._Customer_PO__ != value))
			{
				this._Customer_PO__ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order Date]", Storage="_Order_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Order_Date
	{
		get
		{
			return this._Order_Date;
		}
		set
		{
			if ((this._Order_Date != value))
			{
				this._Order_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDateText", DbType="Char(10)")]
	public string OrderDateText
	{
		get
		{
			return this._OrderDateText;
		}
		set
		{
			if ((this._OrderDateText != value))
			{
				this._OrderDateText = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDateText", DbType="Char(10)")]
	public string DueDateText
	{
		get
		{
			return this._DueDateText;
		}
		set
		{
			if ((this._DueDateText != value))
			{
				this._DueDateText = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Due Date]", Storage="_Due_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Due_Date
	{
		get
		{
			return this._Due_Date;
		}
		set
		{
			if ((this._Due_Date != value))
			{
				this._Due_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Invoice Total]", Storage="_Invoice_Total", DbType="Money NOT NULL")]
	public decimal Invoice_Total
	{
		get
		{
			return this._Invoice_Total;
		}
		set
		{
			if ((this._Invoice_Total != value))
			{
				this._Invoice_Total = value;
			}
		}
	}
}
#pragma warning restore 1591
